spring:
    datasource:
        password: ${DATABASE_PASSWORD}
        username: ${DATABASE_USERNAME}
        url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_POST}/${DATABASE_NAME}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                format_sql: true
                connection:
                    char_set: UTF-8
                hbm2ddl:
                    import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    mail:
        host: smtp.gmail.com
        password: ${MAIL_PASSWORD}
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        requied: true
        username: ${MAIL_USERNAME}
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
            WRITE_DURATIONS_AS_TIMESTAMPS: false


front:
    protocol: ${FRONT_PROTOCOL}
    hostname: ${FRONT_HOSTNAME}
    port: ${FRONT_PORT}